[versions]
kotlin = "2.3.0"

shadow = "9.0.2"

[libraries]
kotlinJvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
